steps:
  - task: DockerInstaller@0
    displayName: Install Docker
    inputs:
      dockerVersion: $(DockerVersion)
      releaseType: stable
        
  - task: Docker@2
    displayName: Docker login
    inputs:
      command: login
      containerRegistry: $(ContainerRegistry)

  - task: CmdLine@2
    displayName: Docker pull
    inputs:
      script: |
        docker pull $(ContainerImage)

  - task: CmdLine@2
    displayName: AzOps Run
    inputs:
      script: |
        docker run --rm \
          --volume=/root:/root \
          --volume=`pwd`:`pwd` \
          --workdir `pwd` \
          --env INPUT_AZURE_CREDENTIALS \
          --env INPUT_GITHUB_EMAIL=$(GitHubEmail) \
          --env INPUT_GITHUB_USERNAME=$(GitHubUserName) \
          --env INPUT_GUTHUB_PULL_REQUEST="Azure Change Notification" \
          --env INPUT_SCMPLATFORM=AzureDevOps \
          --env INPUT_GITHUB_BASE_REF=$(AzopsHeadBranch) \
          --env INPUT_GITHUB_HEAD_REF=$(AzopsHeadBranch) \
          --env INPUT_MODE=$(AzOpsMode) \
          --env INPUT_DEBUG=$(AzOpsDebug) \
          --env INPUT_VERBOSE=$(AzOpsVerbose) \
          --env SYSTEM_PULLREQUEST_PULLREQUESTID \
          --env SYSTEM_TEAMFOUNDATIONCOLLECTIONURI \
          --env SYSTEM_TEAMPROJECTID \
          --env BUILD_REPOSITORY_ID \
          --env SYSTEM_ACCESSTOKEN \
          $(ContainerImage)
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      INPUT_AZURE_CREDENTIALS: $(AzureCredentials)

  - task: Docker@2
    displayName: Docker logout
    inputs:
      command: logout
      containerRegistry: $(ContainerRegistry)
